### ISSUE TITLE
keyValuePairs Support?

### ISSUE THREAD

**Issue by WolfDan** [jamesmacaulay/elm-json-bidirectional#2]
Hello! 

Your work its awesome! I was really tired to write encoder and decoders every time hahahaha, but I like to know is its possible add support to keyValuePairs [(Documentation)](http://package.elm-lang.org/packages/elm-lang/core/5.1.1/Json-Decode#keyValuePairs) I use often this feature

Greetings!

**Comment by jamesmacaulay** [comment]
Great to know that you're finding this useful, thanks!

I can add `keyValuePairs`, yes. I didn't include it initially because it had more potential than most of the other coders to lose information during the encoding process and break the round-trip equality property (a list will have duplicate keys discarded during encoding with `keyValuePairs`, so its decoded value will not always equal the encoded one).

But I think that's fine as long as I put a note in the docs about it. I also wasn't sure how popular `keyValuePairs` was, given the presence of `dict`, so it's good to know that it's wanted :)

I'll add it in the next minor release soon.

**Comment by WolfDan** [comment]
So many thanks!

Also... the only problem to use keyValuePairs its if the keys on the list are duplicated right? Or they are another problems?

**Comment by jamesmacaulay** [comment]
No other problems, no. The thing about duplicate keys is also not very likely to be a problem for people in practice.

**Comment by jamesmacaulay** [comment]
Added in 3452b24, [released in 1.1.0](http://package.elm-lang.org/packages/jamesmacaulay/elm-json-bidirectional/1.1.0/Json-Bidirectional#keyValuePairs)!

**Comment by WolfDan** [comment]
Perfect! So many thanks, here an example with Ellie usign the release 1.1.0!

[Ellie Link](https://ellie-app.com/3dy9t2qg9s4a1/0)
